### PR TITLE
apply to rails3.1

### PR DESCRIPTION
**Pull request by rochefort**
Hi.

It works on Rails3.1, maybe Rails3.2.

### CODE REVIEW

**Comment by kunklejr** [comment]
I'm reluctant to pull this request as it will break apps still running on 3.0.x.

**Comment by rochefort** [comment]
How is this? 
a9264b5abb8a8165b6279fb001d2992602561d2b

If you like it, I send to pull request .

**Comment by kunklejr** [comment]
This looks good. Is there a way to restrict the rails dependency to >= 3.0.0 and < 4.0.0? Either way, a pull request would be greatly appreciated.

**Comment by rochefort** [comment]
ok, done.
#6

**Pull request closed without merging**
